# Generated by Django 5.2.14 on 2026-06-04 14:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('templates', '0014_neutral_ready_flow_coupon_codes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('is_primary', models.BooleanField(default=False, help_text='Workspace principal — fonte de herança de config. Só pode haver um.')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'ordering': ['-is_primary', 'name'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('is_primary',), name='unique_primary_workspace')],
            },
        ),
        migrations.CreateModel(
            name='WorkspaceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inherit_from_primary', models.BooleanField(default=True, help_text='Se True, herda branding/envio/caps do workspace principal.')),
                ('ingest_api_key', models.CharField(blank=True, db_index=True, max_length=80)),
                ('ingest_api_key_created_at', models.DateTimeField(blank=True, null=True)),
                ('ingest_api_key_last_used_at', models.DateTimeField(blank=True, null=True)),
                ('webhook_url', models.URLField(blank=True)),
                ('webhook_events', models.JSONField(blank=True, default=list)),
                ('brand_name', models.CharField(blank=True, max_length=200)),
                ('public_site_url', models.URLField(blank=True)),
                ('deposit_url', models.URLField(blank=True)),
                ('support_url', models.URLField(blank=True)),
                ('unsubscribe_url', models.URLField(blank=True)),
                ('from_email', models.CharField(blank=True, max_length=255)),
                ('from_name', models.CharField(blank=True, max_length=100)),
                ('reply_to', models.CharField(blank=True, max_length=255)),
                ('tracking_base_url', models.URLField(blank=True)),
                ('sms_link_tracking_enabled', models.BooleanField(blank=True, null=True)),
                ('email_daily_cap', models.IntegerField(blank=True, null=True)),
                ('sms_daily_cap', models.IntegerField(blank=True, null=True)),
                ('push_daily_cap', models.IntegerField(blank=True, null=True)),
                ('quiet_hours_start', models.IntegerField(blank=True, null=True)),
                ('quiet_hours_end', models.IntegerField(blank=True, null=True)),
                ('logo_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='templates.emailasset')),
                ('workspace', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='workspaces.workspace')),
            ],
            options={
                'verbose_name': 'Workspace Setting',
                'verbose_name_plural': 'Workspace Settings',
            },
        ),
        migrations.CreateModel(
            name='WorkspaceMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('admin', 'Administrador'), ('member', 'Membro'), ('viewer', 'Leitura')], default='member', max_length=20)),
                ('is_default', models.BooleanField(default=False, help_text='Workspace inicial do usuário ao logar.')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_memberships', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='workspaces.workspace')),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'is_default'], name='workspaces__user_id_ddd9de_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'workspace'), name='unique_membership_per_user_workspace')],
            },
        ),
    ]
