# Generated by Django 5.2.14 on 2026-05-19 00:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('code', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('trigger_type', models.CharField(choices=[('event', 'Event-based'), ('segment_entry', 'Segment entry'), ('scheduled', 'Scheduled')], db_index=True, max_length=20)),
                ('trigger_config', models.JSONField(default=dict, help_text='Ex: {"event_code": "user.register"} ou {"segment_code": "vip"}')),
                ('definition', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(db_index=True, default=False)),
                ('allow_reentry', models.BooleanField(default=False, help_text='Permite usuário entrar novamente após sair?')),
                ('reentry_cooldown_days', models.IntegerField(default=30)),
                ('goal_event_code', models.CharField(blank=True, db_index=True, max_length=100)),
                ('total_enrolled', models.IntegerField(default=0)),
                ('total_completed', models.IntegerField(default=0)),
                ('total_goal_reached', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FlowExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('exited', 'Exited (manual/condition)'), ('goal_reached', 'Goal reached'), ('failed', 'Failed')], db_index=True, default='active', max_length=20)),
                ('current_node_id', models.CharField(default='start', max_length=100)),
                ('next_run_at', models.DateTimeField(db_index=True)),
                ('context', models.JSONField(default=dict)),
                ('trigger_event_id', models.BigIntegerField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('last_node_at', models.DateTimeField(auto_now=True)),
                ('error_message', models.TextField(blank=True)),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='flows.flow')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flow_executions', to='profiles.profile')),
            ],
            options={
                'indexes': [models.Index(fields=['state', 'next_run_at'], name='flows_flowe_state_3fb10f_idx'), models.Index(fields=['flow', 'profile'], name='flows_flowe_flow_id_9d252e_idx'), models.Index(fields=['profile', '-started_at'], name='flows_flowe_profile_e3da5c_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('state', 'active')), fields=('flow', 'profile'), name='unique_active_execution_per_flow_profile')],
            },
        ),
    ]
