# Generated by Django 5.2.14 on 2026-05-29 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flows', '0007_flow_goals_and_ftd_sms'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='flowschedulerun',
            new_name='flows_flows_flow_id_3f0ed0_idx',
            old_name='flows_sched_flow_run_idx',
        ),
    ]
