# Generated by Django 5.2.14 on 2026-06-04 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flows', '0009_ready_flow_coupon_context'),
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flow',
            name='workspace',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='workspaces.workspace'),
        ),
        migrations.AddField(
            model_name='flowexecution',
            name='workspace',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='workspaces.workspace'),
        ),
        migrations.AddField(
            model_name='flowschedulerun',
            name='workspace',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='workspaces.workspace'),
        ),
        migrations.AlterField(
            model_name='flow',
            name='code',
            field=models.SlugField(max_length=100),
        ),
        migrations.AlterField(
            model_name='flow',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AddConstraint(
            model_name='flow',
            constraint=models.UniqueConstraint(fields=('workspace', 'code'), name='unique_flow_code_per_workspace'),
        ),
        migrations.AddConstraint(
            model_name='flow',
            constraint=models.UniqueConstraint(fields=('workspace', 'name'), name='unique_flow_name_per_workspace'),
        ),
    ]
