# Generated by Django 5.2.14 on 2026-05-19 00:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('code', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('rules', models.JSONField(default=dict)),
                ('is_dynamic', models.BooleanField(default=True, help_text='True = recalculado on demand. False = materializado.')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('member_count', models.IntegerField(default=0)),
                ('last_calculated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SegmentMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile')),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='segments.segment')),
            ],
            options={
                'indexes': [models.Index(fields=['segment', '-added_at'], name='segments_se_segment_93064a_idx')],
                'unique_together': {('segment', 'profile')},
            },
        ),
    ]
