# Generated by Django 5.2.14 on 2026-05-19 00:23

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(db_index=True, max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('acquisition', 'Acquisition'), ('engagement', 'Engagement'), ('monetization', 'Monetization'), ('retention', 'Retention'), ('promotion', 'Promotion')], db_index=True, max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('payload_schema', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['category', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_event_id', models.CharField(db_index=True, help_text='ID único do evento na plataforma de origem (idempotência)', max_length=200)),
                ('user_external_id', models.CharField(db_index=True, max_length=100)),
                ('payload', models.JSONField()),
                ('occurred_at', models.DateTimeField(db_index=True, help_text='Quando ocorreu na origem')),
                ('received_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('processed', models.BooleanField(db_index=True, default=False)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('processing_attempts', models.IntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
                ('event_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events.eventtype')),
            ],
            options={
                'ordering': ['-occurred_at'],
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['payload'], name='events_even_payload_03884d_gin'), models.Index(fields=['user_external_id', 'event_type', '-occurred_at'], name='events_even_user_ex_82c338_idx'), models.Index(fields=['processed', 'received_at'], name='events_even_process_2bc37b_idx')],
                'constraints': [models.UniqueConstraint(fields=('event_type', 'external_event_id'), name='unique_event_per_type')],
            },
        ),
    ]
