# Generated by Django 5.2.14 on 2026-06-04 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_update_game_started_schema'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='event',
            name='unique_event_per_type',
        ),
    ]
