# Generated by Django 5.2.14 on 2026-06-04 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_remove_event_unique_event_per_type'),
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='workspace',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='workspaces.workspace'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['workspace', '-occurred_at'], name='events_even_workspa_ffdd40_idx'),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.UniqueConstraint(fields=('workspace', 'event_type', 'external_event_id'), name='unique_event_per_type'),
        ),
    ]
