# Generated by Django 5.2.14 on 2026-05-19 00:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(db_index=True, max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('push', 'Push'), ('whatsapp', 'WhatsApp')], db_index=True, max_length=20)),
                ('category', models.CharField(choices=[('transactional', 'Transactional'), ('marketing', 'Marketing'), ('system', 'System')], default='marketing', max_length=20)),
                ('subject', models.CharField(blank=True, max_length=500)),
                ('html_body', models.TextField(blank=True)),
                ('text_body', models.TextField(blank=True)),
                ('from_email', models.CharField(blank=True, max_length=255)),
                ('from_name', models.CharField(blank=True, max_length=100)),
                ('reply_to', models.CharField(blank=True, max_length=255)),
                ('body', models.TextField(blank=True)),
                ('variables', models.JSONField(blank=True, default=list, help_text='Lista de variáveis usadas (preenchida via parse automático)')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('version', models.IntegerField(default=1)),
                ('include_unsubscribe', models.BooleanField(default=True, help_text='Inclui link de unsubscribe (obrigatório em marketing)')),
            ],
            options={
                'ordering': ['channel', 'code'],
            },
        ),
        migrations.CreateModel(
            name='AbTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=False)),
                ('goal_metric', models.CharField(choices=[('opened', 'Open rate'), ('clicked', 'Click rate'), ('converted', 'Conversion (depósito após envio)')], default='clicked', max_length=50)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_ab_tests', to='templates.messagetemplate')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AbTestVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField(default=50, help_text='Peso no sorteio (1-100)')),
                ('label', models.CharField(blank=True, help_text="Ex: 'A', 'B', 'Control'", max_length=50)),
                ('impressions', models.IntegerField(default=0)),
                ('conversions', models.IntegerField(default=0)),
                ('ab_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='templates.abtest')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='templates.messagetemplate')),
            ],
            options={
                'unique_together': {('ab_test', 'template')},
            },
        ),
    ]
