# Generated by Django 5.2.14 on 2026-05-22 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0004_update_assertive_coupons'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignCoupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.SlugField(help_text="Chave interna usada nos flows (ex: 'welcome', 'winback_gamer')", max_length=80, unique=True)),
                ('code', models.CharField(help_text='Código real que o jogador insere ao depositar (ex: BOAS100)', max_length=100)),
                ('description', models.CharField(blank=True, help_text='Descrição interna da campanha', max_length=300)),
                ('flow_code', models.CharField(blank=True, db_index=True, help_text='Código do flow ao qual este cupom pertence (referência, não FK)', max_length=100)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Cupom desativado automaticamente após esta data/hora', null=True)),
            ],
            options={
                'ordering': ['key'],
            },
        ),
    ]
