# Generated by Django 5.2.14 on 2026-06-04 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0014_neutral_ready_flow_coupon_codes'),
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='abtest',
            name='workspace',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='workspaces.workspace'),
        ),
        migrations.AddField(
            model_name='campaigncoupon',
            name='workspace',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='workspaces.workspace'),
        ),
        migrations.AddField(
            model_name='emailasset',
            name='workspace',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='workspaces.workspace'),
        ),
        migrations.AddField(
            model_name='messagetemplate',
            name='workspace',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='workspaces.workspace'),
        ),
        migrations.AlterField(
            model_name='campaigncoupon',
            name='key',
            field=models.SlugField(help_text="Chave interna usada nos flows (ex: 'welcome', 'winback_gamer')", max_length=80),
        ),
        migrations.AlterField(
            model_name='messagetemplate',
            name='code',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AddConstraint(
            model_name='campaigncoupon',
            constraint=models.UniqueConstraint(fields=('workspace', 'key'), name='unique_coupon_key_per_workspace'),
        ),
        migrations.AddConstraint(
            model_name='messagetemplate',
            constraint=models.UniqueConstraint(fields=('workspace', 'code'), name='unique_template_code_per_workspace'),
        ),
    ]
