# Generated by Django 5.2.14 on 2026-05-19 00:23

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('external_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('push_token', models.CharField(blank=True, max_length=500, null=True)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('country', models.CharField(default='BR', max_length=2)),
                ('state', models.CharField(blank=True, max_length=2)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('total_deposits', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_withdrawals', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('deposit_count', models.IntegerField(default=0)),
                ('withdrawal_count', models.IntegerField(default=0)),
                ('failed_deposit_count', models.IntegerField(default=0)),
                ('ftd_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_deposit_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_login_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_event_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('registered_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('favorite_game', models.CharField(blank=True, max_length=100)),
                ('ltv', models.DecimalField(decimal_places=2, default=0, help_text='Lifetime Value (= total_deposits - total_withdrawals)', max_digits=14)),
                ('ngr', models.DecimalField(decimal_places=2, default=0, help_text='Net Gaming Revenue (LTV - bônus pagos)', max_digits=14)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('custom_attributes', models.JSONField(blank=True, default=dict)),
                ('consent_email', models.BooleanField(default=False)),
                ('consent_sms', models.BooleanField(default=False)),
                ('consent_push', models.BooleanField(default=False)),
                ('consent_whatsapp', models.BooleanField(default=False)),
                ('email_bounce_count', models.IntegerField(default=0)),
                ('sms_bounce_count', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['ltv'], name='profiles_pr_ltv_09a4ff_idx'), models.Index(fields=['ftd_at'], name='profiles_pr_ftd_at_177c5f_idx'), models.Index(fields=['last_login_at'], name='profiles_pr_last_lo_ebd0c0_idx'), django.contrib.postgres.indexes.GinIndex(fields=['tags'], name='profiles_pr_tags_770a41_gin'), django.contrib.postgres.indexes.GinIndex(fields=['custom_attributes'], name='profiles_pr_custom__188741_gin')],
            },
        ),
    ]
