# Generated by Django 5.2.14 on 2026-05-21 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_add_import_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='favorite_game_category',
            field=models.CharField(blank=True, help_text='Categoria com mais sessões: slots, crash, live_casino, table', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='favorite_game_provider',
            field=models.CharField(blank=True, help_text='Provedor com mais sessões: pragmatic_play, evolution, spribe…', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='game_session_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_game_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='preferred_play_hour',
            field=models.IntegerField(blank=True, help_text='Hora do dia (0-23) com maior frequência de sessões — usado para send-time optimization', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='total_wagered',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Soma de todos os bet_amount recebidos em game.started', max_digits=14),
        ),
    ]
