# Generated by Django 5.2.14 on 2026-06-04 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_default_profile_consents'),
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='workspace',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='workspaces.workspace'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='external_id',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['workspace', 'external_id'], name='profiles_pr_workspa_600910_idx'),
        ),
        migrations.AddConstraint(
            model_name='profile',
            constraint=models.UniqueConstraint(fields=('workspace', 'external_id'), name='unique_external_id_per_workspace'),
        ),
    ]
