# Generated by Django 5.2.14 on 2026-05-19 00:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('push', 'Push'), ('whatsapp', 'WhatsApp')], db_index=True, max_length=20)),
                ('provider_class', models.CharField(choices=[('PostalEmailProvider', 'Postal (self-hosted)'), ('MailgunEmailProvider', 'Mailgun'), ('SmtpEmailProvider', 'SMTP genérico'), ('WebhookSmsProvider', 'Webhook genérico (FluxLab, etc)'), ('ZenviaSmsProvider', 'Zenvia'), ('TwilioSmsProvider', 'Twilio'), ('FcmPushProvider', 'Firebase Cloud Messaging')], max_length=100)),
                ('config', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('priority', models.IntegerField(default=100, help_text='Menor = mais prioritário')),
                ('daily_quota', models.IntegerField(blank=True, null=True)),
                ('monthly_quota', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['channel', 'priority', 'name'],
                'indexes': [models.Index(fields=['channel', 'is_active', 'priority'], name='messaging_p_channel_fe2a77_idx')],
            },
        ),
        migrations.CreateModel(
            name='MessageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(db_index=True, max_length=20)),
                ('recipient', models.CharField(help_text='Email, telefone ou device token', max_length=255)),
                ('template_code', models.CharField(db_index=True, max_length=100)),
                ('subject', models.CharField(blank=True, max_length=500)),
                ('body_preview', models.CharField(blank=True, max_length=200)),
                ('external_message_id', models.CharField(blank=True, db_index=True, max_length=200)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('opened', 'Opened'), ('clicked', 'Clicked'), ('bounced', 'Bounced'), ('failed', 'Failed'), ('complained', 'Complained'), ('unsubscribed', 'Unsubscribed'), ('rejected', 'Rejected')], db_index=True, default='queued', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('raw_response', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('sent_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('clicked_at', models.DateTimeField(blank=True, null=True)),
                ('bounced_at', models.DateTimeField(blank=True, null=True)),
                ('flow_execution_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('campaign_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='profiles.profile')),
                ('provider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='messages', to='messaging.providerconfig')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['profile', 'channel', '-created_at'], name='messaging_m_profile_f20f40_idx'), models.Index(fields=['status', 'channel'], name='messaging_m_status_2cc6b0_idx'), models.Index(fields=['template_code', '-created_at'], name='messaging_m_templat_911984_idx')],
            },
        ),
    ]
