# Generated by Django 5.2.14 on 2026-05-21 02:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('headers', models.JSONField(default=dict)),
                ('payload', models.JSONField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processed', 'Processed'), ('failed', 'Failed'), ('ignored', 'Ignored')], db_index=True, default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('message_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhook_events', to='messaging.messagelog')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='webhook_events', to='messaging.providerconfig')),
            ],
            options={
                'ordering': ['-received_at'],
                'indexes': [models.Index(fields=['provider', '-received_at'], name='messaging_w_provide_79632f_idx'), models.Index(fields=['status', '-received_at'], name='messaging_w_status_af243f_idx')],
            },
        ),
    ]
