# Generated by Django 5.2.14 on 2026-06-13 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0004_trackedlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagelog',
            name='retry_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='messagelog',
            name='send_kwargs',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
