# Generated by Django 5.2.14 on 2026-06-04 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0004_trackedlink'),
        ('profiles', '0006_profile_workspace_alter_profile_external_id_and_more'),
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagelog',
            name='workspace',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='workspaces.workspace'),
        ),
        migrations.AddField(
            model_name='providerconfig',
            name='workspace',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='workspaces.workspace'),
        ),
        migrations.AlterField(
            model_name='providerconfig',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AddIndex(
            model_name='messagelog',
            index=models.Index(fields=['workspace', '-created_at'], name='messaging_m_workspa_7b0b14_idx'),
        ),
        migrations.AddIndex(
            model_name='providerconfig',
            index=models.Index(fields=['workspace', 'channel', 'is_active', 'priority'], name='messaging_p_workspa_384672_idx'),
        ),
        migrations.AddConstraint(
            model_name='providerconfig',
            constraint=models.UniqueConstraint(fields=('workspace', 'name'), name='unique_provider_name_per_workspace'),
        ),
    ]
