# Generated by Django 5.2.14 on 2026-06-04 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0005_messagelog_workspace_providerconfig_workspace_and_more'),
        ('workspaces', '0002_backfill_workspace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagelog',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='workspaces.workspace'),
        ),
        migrations.AlterField(
            model_name='providerconfig',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='workspaces.workspace'),
        ),
    ]
